<?php

/**
 * @file
 * To add single or multiple classes to body tag for the selected pages.
 */

use Drupal\Core\Url;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_preprocess_html().
 */
function multiple_class_preprocess_html(&$variables) {

  // Get the current route name.
  $route_name = \Drupal::service('path.current')->getPath();

  // Get pages from multiple class form settings.
  $config = \Drupal::config('multiple_class.settings');

  if (!empty($config->get('add_more'))) {

    $get_data = $config->get('add_more');
    foreach ($get_data as $value) {
      $url = $value['extra_path'];
      $add_class = $value['extra_class'];
      $check_wildcard = FALSE;
      $front_page = \Drupal::service('path.matcher')->isFrontPage();
      $enteredPath = \Drupal::service('path_alias.manager')->getPathByAlias($url);
      $alias_path = \Drupal::service('path_alias.manager')->getAliasByPath($route_name);

      // Check wildcard.
      if (strpos($url, '*') !== FALSE) {
        $path = str_replace('/*', '', $url);
        $path = str_replace('*', '', $path);
        if (strpos($alias_path, $path) === 0) {
          $check_wildcard = TRUE;
        }
      }

      // Add class only if  current path and entered path by user matches.
      if (($route_name == $enteredPath) || ($check_wildcard)) {
        $variables['attributes']['class'][] = $add_class;
      }

      // Add class only if current page matches with home page.
      if (($front_page) && ($enteredPath == "<front>")) {
        $variables['attributes']['class'][] = $add_class;
      }

      // user entered path for all.
      if (($enteredPath == "/*")) {
        $variables['attributes']['class'][] = $add_class;
      }
    }
  }
}
