<?php

/**
 * @file
 * To add single or multiple classes to body tag for the selected pages.
 */

use Drupal\Core\Url;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_preprocess_html().
 */
function multiple_class_preprocess_html(&$variables) {

  // Get the current route name.
  $route_name = \Drupal::service('path.current')->getPath();

  // Get page settings from multiple class form.
  $config = \Drupal::config('multiple_class.settings');
  $get_pages = explode(PHP_EOL, $config->get('specific_pages'));

  // Get classes settings from multiple class form.
  $get_classes = $config->get('add_class');
  $add_class = '';
  foreach ($get_classes as $class) {
    $add_class .= $class['extra_class'] . '  ';
  }

  foreach ($get_pages as $url) {

   $check_wildcard = FALSE;
   $front_page = \Drupal::service('path.matcher')->isFrontPage();
   $enteredPath = \Drupal::service('path_alias.manager')->getPathByAlias($url);
   $alias_path = \Drupal::service('path_alias.manager')->getAliasByPath($route_name);

   // Check wildcard.
   if (strpos($url, '*') !== FALSE) {
     $path = str_replace('/*', '', $url);
     $path = str_replace('*', '', $path);
     if (strpos($alias_path, $path) === 0) {
        $check_wildcard = TRUE;
     }
   }

   // Add class only if  current path and entered path by user matches.
   if (($route_name == $enteredPath) || ($check_wildcard)) {
     $variables['attributes']['class'][] = $add_class;
   }

   // Add class only if current page matches with home page or user entered path for all.
   elseif (($front_page) || ($enteredPath == "/*")) {
     $variables['attributes']['class'][] = $add_class;
   }
  }
}
